### PR TITLE
Added index on state for minion_jobs

### PR DESCRIPTION
**Pull request by avkhozov**
I have an minion_jobs table with 300k rows (with same day, so remove_after not actual) and worker with 64 concurrently jobs. Query for get new job take 100ms and this seems slow. Index on state of job can help.

```sql
cs=> explain analyze select id from minion_jobs
  where state = 'inactive' and delayed < now() and task = any ('{sla,check,flag_points,scoreboard}')
  order by priority desc, created
  limit 1;
                                                                QUERY PLAN                                                                
------------------------------------------------------------------------------------------------------------------------------------------
 Limit  (cost=34642.46..34642.46 rows=1 width=20) (actual time=100.485..100.485 rows=0 loops=1)
   ->  Sort  (cost=34642.46..34642.46 rows=1 width=20) (actual time=100.483..100.483 rows=0 loops=1)
         Sort Key: priority, created
         Sort Method: quicksort  Memory: 25kB
         ->  Seq Scan on minion_jobs  (cost=0.00..34642.44 rows=1 width=20) (actual time=100.470..100.470 rows=0 loops=1)
               Filter: ((state = 'inactive'::text) AND (delayed < now()) AND (task = ANY ('{sla,check,flag_points,scoreboard}'::text[])))
               Rows Removed by Filter: 362374
 Planning time: 0.294 ms
 Execution time: 100.531 ms
(9 rows)
cs=> create index on minion_jobs (state);
CREATE INDEX
cs=> explain analyze select id from minion_jobs
  where state = 'inactive' and delayed < now() and task = any ('{sla,check,flag_points,scoreboard}')
  order by priority desc, created
  limit 1;
                                                                   QUERY PLAN                                                                   
------------------------------------------------------------------------------------------------------------------------------------------------
 Limit  (cost=4.46..4.46 rows=1 width=20) (actual time=0.058..0.058 rows=0 loops=1)
   ->  Sort  (cost=4.46..4.46 rows=1 width=20) (actual time=0.055..0.055 rows=0 loops=1)
         Sort Key: priority, created
         Sort Method: quicksort  Memory: 25kB
         ->  Index Scan using minion_jobs_state_idx on minion_jobs  (cost=0.42..4.45 rows=1 width=20) (actual time=0.041..0.041 rows=0 loops=1)
               Index Cond: (state = 'inactive'::text)
               Filter: ((delayed < now()) AND (task = ANY ('{sla,check,flag_points,scoreboard}'::text[])))
 Planning time: 0.613 ms
 Execution time: 0.113 ms
(9 rows)
```

### CODE REVIEW

**Comment by avkhozov** [comment]
Also this index can affect on https://github.com/kraih/minion/blob/master/lib/Minion/Backend/Pg.pm#L149 query

**Comment by kraih** [comment]
Seems reasonable.

**Comment by avkhozov** [comment]
Thanks!

**Comment by avkhozov** [comment]
It seems that after 74bddca37e02743744145a4431a22040151a03d5 index minion_jobs_state_idx is no longer used.

**Comment by kraih** [comment]
Yes, i'm seeing this too.

**Comment by kraih** [comment]
I've removed the index for now, if you have any ideas for a replacement, please let me know. https://github.com/kraih/minion/commit/5a34321f8e74cb627bb76feae09fafd6ba00255e

**Comment by avkhozov** [comment]
Ok, I'll investigate this later. Also index for sorting (priority and created fields) seems not being using too.

**Comment by kraih** [comment]
That doesn't appear to be true.
```
test=# explain analyze select id from minion_jobs where state = 'inactive' and delayed < now() and task = any ('{foo,bar,baz,yada}') and queue = 'default' order by priority desc, created limit 1;
QUERY PLAN                                                                        
----------------------------------------------------------------------------------------------------------------------------------------------------------
 Limit  (cost=0.29..0.45 rows=1 width=20) (actual time=3.622..3.622 rows=1 loops=1)
   ->  Index Scan using minion_jobs_priority_created_idx on minion_jobs  (cost=0.29..822.10 rows=5000 width=20) (actual time=3.621..3.621 rows=1 loops=1)
         Filter: ((state = 'inactive'::text) AND (queue = 'default'::text) AND (delayed < now()) AND (task = ANY ('{foo,bar,baz,yada}'::text[])))
         Rows Removed by Filter: 5000
 Planning time: 0.251 ms
 Execution time: 3.688 ms
(6 rows)
```

**Comment by avkhozov** [comment]
Yes, I was wrong.

**Pull request merged**
