### PR TITLE
restart sequences for jobs when reset queue

### PR DESCRIPTION
**Pull request by avkhozov**
This can be useful for tests.

### CODE REVIEW

**Comment by kraih** [comment]
How so? The patch does not even include any tests.

**Comment by kraih** [comment]
Different backends will handle id generation completely different (already the case with the `DBM::Deep` backend), so depending on how one backend does it in your tests seems like a pretty bad idea.

**Comment by avkhozov** [comment]
The expected ids of jobs can be useful in some cases in tests, but this is not critical feature. Yes, this will work only in Pg backend, but backend usually selects a one time for project and then have not changing.

**Comment by avkhozov** [comment]
And these changes simply will look more consistent. I can add tests if necessary to accept the changes.

**Comment by kraih** [comment]
I'm afraid without a good use case i have to give this a :-1:.

**Pull request closed without merging**
