### PR TITLE
set new random seed for each job

### PR DESCRIPTION
**Pull request by avkhozov**

### CODE REVIEW

**Comment by avkhozov** [comment]
Usefull, to not do this in each minion task.

**Comment by jberger** [comment]
By project rules, in order for this to be considered a feature it would need tests and documentation. As this change serves no purpose to the internals it must only be considered as a feature and without those it doesn't qualify out of hand.

**Comment by kraih** [comment]
This should be very easy to test, but i can't think of that many use cases.

**Comment by kraih** [comment]
@avkhozov Meta comment: You're not doing yourself a favor sending pull requests without descriptions. That only makes it so much harder for people to comment and/or vote.

**Comment by kraih** [comment]
As it stands, i'm afraid i have to close this pull request because it is incomplete.

**Comment by avkhozov** [comment]
@jberger I thought that this change is very similar to the calling ``srand`` in ``Mojo::Server::Prefork`` (https://github.com/kraih/mojo/blob/master/lib/Mojo/Server/Prefork.pm#L161), which does not described in documentation and does not affect tests (without ``srand`` all tests passed).

@kraih Sorry for missing description. I think if ``Minion`` does ``fork``, that it needs to cleanup the environment. I think it is implied that each jobs has its own random number generator seed. There are a lot of modules on cpan, which requires to call ``srand`` in each task: ``String::Random``, ``Data::Random``, another ``*::Random::*``, may be some ``*UUID*`` modules, even ``Mango::BSON::ObjectID``:

```bash
$ cat 1.pl
use Mojolicious::Lite;
use Mango::BSON ':bson';

plugin Minion => {Pg => 'postgresql://and@/test'};
app->minion->add_task(test => sub { warn "$$ " . bson_oid });

app->start;
$ for a in {1..10}; do perl 1.pl minion job -e test; done
40011
40012
40013
40014
40015
40016
40017
40018
40019
40020
$ perl 1.pl minion worker -j 20
21667 56a31752c822c154a0b0a1a7 at 1.pl line 5, <DATA> line 729.
21668 56a31752c822c154a0b0a1a7 at 1.pl line 5, <DATA> line 729.
21669 56a31752c822c154a0b0a1a7 at 1.pl line 5, <DATA> line 729.
21670 56a31752c822c154a0b0a1a7 at 1.pl line 5, <DATA> line 729.
21671 56a31752c822c154a0b0a1a7 at 1.pl line 5, <DATA> line 729.
21672 56a31752c822c154a0b0a1a7 at 1.pl line 5, <DATA> line 729.
21673 56a31752c822c154a0b0a1a7 at 1.pl line 5, <DATA> line 729.
21674 56a31752c822c154a0b0a1a7 at 1.pl line 5, <DATA> line 729.
21675 56a31752c822c154a0b0a1a7 at 1.pl line 5, <DATA> line 729.
21676 56a31752c822c154a0b0a1a7 at 1.pl line 5, <DATA> line 729.
^C
$ 
```

This is not a problem in ``Minion``, but it would be convenient if ``Mininon`` do that (calling ``srand``). May be ``Minion`` could present hook or event ``after_fork`` which could be written once for all tasks and everyone will be able configure the environment manually.

**Comment by kraih** [comment]
In `Mojo::Server::Prefork` it is actually required to make sure that not all worker processes restart at once.

**Comment by kraih** [comment]
Regarding the event, i think that might be a good idea, but i can't think of a good name that fits. :smiley:

**Comment by avkhozov** [comment]
``$minion->on(spawn => sub {})``
``$minion->on(fork => sub {})``
``$minion->on(child => sub {})``
``$minion->on(start => sub {})``
``$minion->on(job => sub {})``
``$minion->on(before_job => sub {})``
``$minion->on(init_job => sub {})``
:smirk:

**Pull request closed without merging**
