### PR TITLE
Worker and job classes for extensibility

### PR DESCRIPTION
**Pull request by aferreira**
### Summary
This adds `job_class` and `worker_class` to Minion with the natural defaults as `Minion::Job` and `Minion::Worker`.

### Motivation
It makes easier to introduce small behavior changes with custom job and worker classes.

### References
none so far

### Caveats
A very simple test has been added.

### CODE REVIEW

**Comment by kraih** [comment]
I can see use cases for a configurable job class, perhaps even task specific job classes, but changing the worker class does not make much sense to me.

**Comment by aferreira** [comment]
My use case was to create workers with different default queues than "default". That way, across colaborating applications, I could start workers with

      ./app.pl minion worker

and the right queue would be established without having to remember the proper `-q QUEUE` to go with that.

**Comment by aferreira** [comment]
The ability to extend the worker class also makes easier to do stuff like augmenting worker info (for example, by adding "queues" & other information) without needing Minion core to support that.   (That would allow https://github.com/kraih/minion/issues/44 as a local extension that could implemented now instead of waiting for the general solution about an improved worker info API.)

**Comment by kraih** [comment]
I don't feel confident enough with the current worker API to encourage this kind of customization, afraid i'll have to give this a 👎 for now.

**Comment by jberger** [comment]
> My use case was to create workers with different default queues than "default". That way, across colaborating applications, I could start workers with
>
>  ./app.pl minion worker
>
> and the right queue would be established without having to remember the proper -q QUEUE to go with that.

On rereading this, I went and checked the code. The queues to check isn't a property of the worker, it is a property of the worker command (used [here](https://github.com/kraih/minion/blob/59748c62a63304bce5b63dcf04b0393edba2bb5c/lib/Minion/Command/minion/worker.pm#L77)).

Therefore, if the proposed solution here doesn't fix the mentioned problem, I guess I'm :-1: as well.

**Comment by kraih** [comment]
Thank you for your contribution, but i'm afraid this pull request did not reach the required number of votes. You might like the new worker status feature we are testing at the moment though. https://github.com/kraih/minion/commit/d81cb2aa21567a849f7ce593b87a61b8c4668d23

**Pull request closed without merging**
