### PR TITLE
Make worker stops faster

### PR DESCRIPTION
**Pull request by aferreira**
This change makes immediate (QUIT) and graceful (TERM, INT)
stops faster.  While stopping, the worker won't
do repairs. For immediate stops, it won't
send heartbeats or process remote commands either.

Also adds worker log messages for "stopping".

### Summary

This started with the discussion around https://github.com/kraih/minion/pull/54

Looking for a way to make the signal handlers as simple as possible, I found that the work loop:

```
eval { $self->_work until $self->{finished} && !keys %{$self->{jobs}}; 1 }
```

would make a stopping worker to go through the usual work steps before leaving, including
* (possibly) send a heartbeat
* (possibly) process remote commands
* (possibly) run a repair
* check on finished jobs
* sleep a second

This change reduces the steps the worker goes thru while stopping.

* it stops running repairs for all stops

* it also stops sending heartbeats and processing commands for immediate stops

* when all jobs have finished, a stopping worker will quit promptly (without sleeping)

_Updated at 2017-07-29_

### CODE REVIEW

**Comment by kraih** [comment]
Stopping the worker process before the jobs seems more like a bug than a feature to me.

**Comment by aferreira** [comment]
> Stopping the worker process before the job processes

I don't think the changed code does  anything with respect to this worse than the previous code:

* when QUIT is received, KILL is sent to children (they won't have a chance to recover) – there is nothing in $job->is_finished() or $worker->unregister() that softens this immediate stop

* when TERM or INT is received, work will continue for a graceful stop until all children are detected as is_finished()

**Comment by kraih** [comment]
Afraid you're wrong. The worker process no longer records the exit status of the stopped job processes after this patch.

**Comment by aferreira** [comment]
Now I see my oversight about the side effects of $job->is_finished(). I am going to write a fix.

**Comment by aferreira** [comment]
The use of "next_*" variables also makes much easier to go a further step and allow workers which skip some processing – I think the most useful is a worker which does not do repairs. (Not sending heartbeats and processing commands is not such a good idea – as it creates an unresponsive worker.)

**Comment by kraih** [comment]
Afraid i have to reject this pull request. Your proposed changes would break the use of remote control commands to change intervals on the fly.

**Comment by kraih** [comment]
And before you resubmit a different variation of these changes, perhaps we should talk about them on IRC. Because i don't think i agree with your plans.

**Pull request closed without merging**
